// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdhNwqnOHEu7zl0DI1ga6hOnczhCoo0co',
    appId: '1:286054429599:web:d6175a31a341ac7b1d83aa',
    messagingSenderId: '286054429599',
    projectId: 'songcatcher-fcf35',
    authDomain: 'songcatcher-fcf35.firebaseapp.com',
    databaseURL: 'https://songcatcher-fcf35-default-rtdb.firebaseio.com',
    storageBucket: 'songcatcher-fcf35.firebasestorage.app',
    measurementId: 'G-3NLHNM9F7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBadZWtSdXTvUCtx2OKC8j7KfTavhQa8BY',
    appId: '1:286054429599:android:eeb340a4701bdce31d83aa',
    messagingSenderId: '286054429599',
    projectId: 'songcatcher-fcf35',
    databaseURL: 'https://songcatcher-fcf35-default-rtdb.firebaseio.com',
    storageBucket: 'songcatcher-fcf35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8z_lRPyhShU69Cg-RjGySZ9jjOYutc1M',
    appId: '1:286054429599:ios:adf6c53313de2c281d83aa',
    messagingSenderId: '286054429599',
    projectId: 'songcatcher-fcf35',
    databaseURL: 'https://songcatcher-fcf35-default-rtdb.firebaseio.com',
    storageBucket: 'songcatcher-fcf35.firebasestorage.app',
    iosClientId: '286054429599-k5jg7935bugrucnd35g9k3b2mmjn383c.apps.googleusercontent.com',
    iosBundleId: 'com.example.songcatcher',
  );
}
